#pragma once

#include <stdio.h>
#include <stdlib.h>
#include <GL/glew.h>
#include <GL/freeglut.h>
#include <FreeImage/FreeImage.h>

#include "Shaders/LoadShaders.h"
#include "My_Shading.h"
#include <time.h>

#include <glm/gtc/matrix_transform.hpp> //translate, rotate, scale, lookAt, perspective, etc.
#include <glm/gtc/matrix_inverse.hpp> // inverseTranspose, etc.

#define N_NORMAL_TEXTURES_USED 42

#define TEXTURE_INDEX_ORIGINAL 0
#define TEXTURE_INDEX_TEST 1


#define TEXTURE_INDEX_COMPRESS_TEST1 2
#define TEXTURE_INDEX_COMPRESS_TEST2 3
#define TEXTURE_INDEX_COMPRESS_TEST3 4
#define TEXTURE_INDEX_COMPRESS_TEST4 5
#define TEXTURE_INDEX_COMPRESS_TEST5 6
#define TEXTURE_INDEX_COMPRESS_TEST6 7
#define TEXTURE_INDEX_COMPRESS_TEST7 8
#define TEXTURE_INDEX_COMPRESS_TEST8 9
#define TEXTURE_INDEX_COMPRESS_TEST9 10
#define TEXTURE_INDEX_COMPRESS_TEST10 11
#define TEXTURE_INDEX_COMPRESS_TEST11 12
#define TEXTURE_INDEX_COMPRESS_TEST12 13
#define TEXTURE_INDEX_COMPRESS_TEST13 14
#define TEXTURE_INDEX_COMPRESS_TEST14 15
#define TEXTURE_INDEX_COMPRESS_TEST15 16
#define TEXTURE_INDEX_COMPRESS_TEST16 17
#define TEXTURE_INDEX_COMPRESS_TEST17 18
#define TEXTURE_INDEX_COMPRESS_TEST18 19
#define TEXTURE_INDEX_COMPRESS_TEST19 20
#define TEXTURE_INDEX_COMPRESS_TEST20 21


#define TEXTURE_INDEX_ORIGINAL_TEST1 22
#define TEXTURE_INDEX_ORIGINAL_TEST2 23
#define TEXTURE_INDEX_ORIGINAL_TEST3 24
#define TEXTURE_INDEX_ORIGINAL_TEST4 25
#define TEXTURE_INDEX_ORIGINAL_TEST5 26
#define TEXTURE_INDEX_ORIGINAL_TEST6 27
#define TEXTURE_INDEX_ORIGINAL_TEST7 28
#define TEXTURE_INDEX_ORIGINAL_TEST8 29
#define TEXTURE_INDEX_ORIGINAL_TEST9 30
#define TEXTURE_INDEX_ORIGINAL_TEST10 31
#define TEXTURE_INDEX_ORIGINAL_TEST11 32
#define TEXTURE_INDEX_ORIGINAL_TEST12 33
#define TEXTURE_INDEX_ORIGINAL_TEST13 34
#define TEXTURE_INDEX_ORIGINAL_TEST14 35
#define TEXTURE_INDEX_ORIGINAL_TEST15 36
#define TEXTURE_INDEX_ORIGINAL_TEST16 37
#define TEXTURE_INDEX_ORIGINAL_TEST17 38
#define TEXTURE_INDEX_ORIGINAL_TEST18 39
#define TEXTURE_INDEX_ORIGINAL_TEST19 40
#define TEXTURE_INDEX_ORIGINAL_TEST20 41


float load_unpack_image(const char *filename);
float load_astc_image(const char *filename);
float load_dds_image(const char * imagepath);
double getPSNR(const char* fileName1, const char* fileName2);